# Generated by Django 6.0.3 on 2026-03-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('post_grad', models.IntegerField(choices=[(1, 'Coronel'), (2, 'Tenente-Coronel'), (3, 'Major'), (4, 'Capitão'), (5, '2º Tenente'), (6, '1º Tenente'), (7, 'Aspirante'), (8, 'Subtenente'), (9, '1º Sargento'), (10, '2º Sargento'), (11, '3º Sargento'), (12, 'Cabo'), (13, 'Soldado')], default=1, verbose_name='Posto/Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('senha', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
        migrations.CreateModel(
            name='Conscrito',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('ra', models.CharField(blank=True, max_length=12, null=True)),
                ('pai', models.CharField(blank=True, max_length=100, null=True)),
                ('mae', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=12, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('escolaridade', models.IntegerField(choices=[(1, 'Fundamental Incompleto'), (2, 'Fundamental Completo'), (3, 'Médio Incompleto'), (4, 'Médio Completo'), (5, 'Superior Incompleto'), (6, 'Superior Completo')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('telefone_pessoal', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='app.estado')),
            ],
        ),
        migrations.AddField(
            model_name='conscrito',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipio'),
        ),
    ]
