# Generated by Django 6.0.3 on 2026-05-03 17:33

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conscrito',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('ra', models.CharField(blank=True, max_length=12, null=True, verbose_name='RA')),
                ('pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('rg_orgao_emissor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor do RG')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=12, null=True, verbose_name='Título de Eleitor')),
                ('titulo_zona', models.CharField(blank=True, max_length=3, null=True, verbose_name='Zona Eleitoral')),
                ('titulo_secao', models.CharField(blank=True, max_length=4, null=True, verbose_name='Seção Eleitoral')),
                ('cnh', models.IntegerField(choices=[(1, 'Não Possuo CNH'), (2, 'Categoria A'), (3, 'Categoria B'), (4, 'Categoria C'), (5, 'Categoria D'), (6, 'Categoria E'), (7, 'Categorias A e B'), (8, 'Categorias A e C'), (9, 'Categorias A e D'), (10, 'Categorias A e E')], default=1, verbose_name='CNH / Categoria')),
                ('escolaridade', models.IntegerField(choices=[(1, 'Fundamental Incompleto'), (2, 'Fundamental Completo'), (3, 'Médio Incompleto'), (4, 'Médio Completo'), (5, 'Superior Incompleto'), (6, 'Superior Completo')], default=4)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('post_grad', models.IntegerField(choices=[(1, 'Coronel'), (2, 'Tenente-Coronel'), (3, 'Major'), (4, 'Capitão'), (5, '1º Tenente'), (6, '2º Tenente'), (7, 'Aspirante'), (8, 'Subtenente'), (9, '1º Sargento'), (10, '2º Sargento'), (11, '3º Sargento'), (12, 'Cabo'), (13, 'Soldado')], null=True, verbose_name='Posto/Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
                'ordering': ['post_grad', 'nome_guerra'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Composicao_Familiar',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('moradia', models.IntegerField(choices=[(1, 'Imóvel Próprio'), (2, 'Imóvel Alugado'), (3, 'Outro')], verbose_name='Tipo de Moradia')),
                ('sustento', models.BooleanField(verbose_name='Contribui para o sustento da família?')),
                ('contribuicao', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Contribuição mensal (R$)')),
                ('arrimo', models.IntegerField(choices=[(1, 'Não se enquadra.'), (2, 'Filho único de mulher viúva ou solteira, da abandonada pelo marido ou da desquitada, à qual sirva de único arrimo ou o que ela escolher quando tiver mais de um, sem direito a outra opção.'), (3, 'Filho que sirva de único arrimo ao pai fìsicamente incapaz para prover o seu sustento.'), (4, 'Viúvo ou desquitado que tiver filho menor (legítimo ou legitimado) de que seja único arrimo.'), (5, 'Casado que sirva de único arrimo à esposa ou à esposa e filho menor (legítimo ou legitimado).'), (6, 'Solteiro que tiver filho menor (legalmente reconhecido) de que seja único arrimo.'), (7, 'Órfão de pai e mãe que sustente irmão menor, ou maior inválido ou interdito, ou ainda irmã solteira ou viúva que viva em sua companhia.'), (8, 'Órfão de pai e mãe, que sirva de único arrimo a uma de suas avós ou avô decrépito ou valetudinário, incapaz de prover os meios de subsistência.')], verbose_name='Situação de Arrimo')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('telefone_pessoal', models.CharField(max_length=15, verbose_name='Telefone')),
                ('telefone_emergencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato de Emergência')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFardamento',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('calcado', models.PositiveIntegerField(verbose_name='Número do Calçado')),
                ('gorro', models.PositiveIntegerField(verbose_name='Tamanho do Gorro')),
                ('boina', models.PositiveIntegerField(verbose_name='Tamanho da Boina')),
                ('tfm', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme de TFM')),
                ('camuflado', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme camuflado')),
                ('passeio', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme de passeio')),
                ('jaquela', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho da jaqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Particularidades',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('relacao_familiar', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento familiar')),
                ('relacao_social', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento social')),
                ('sv_militar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alguém da família já serviu às Forças Armadas ou trabalhou em Órgão de Segurança Pública? (EB, MB, FAB, PM, Polícia Civil, GCM)')),
                ('armas_fogo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já utilizou qualquer tipo de arma de fogo?')),
                ('voluntario', models.BooleanField(verbose_name='Deseja servir voluntariamente?')),
                ('voluntario_justificativa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Justifique sua resposta anterior:')),
            ],
        ),
        migrations.CreateModel(
            name='Psicossocial',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('drogas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já consumiu ou consome drogas?')),
                ('jogos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de jogos de azar?')),
                ('movimentos_sociais', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos sociais?')),
                ('movimentos_politicos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos políticos?')),
                ('movimentos_religiosos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos religiosos?')),
                ('osp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Você ou alguém da família já se envolveu com Órgãos de Segurança Pública, mesmo na condição de testemunha?')),
                ('trafico_proximidades', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nas proximidades do local onde reside existem problemas com relação a tráfico ou consumo de drogas?')),
                ('acao_justica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Possui ações na justiça contra o estado ou a nível federal?')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Entrevista'), (2, 'Avaliação Médica'), (3, 'Avaliação Odontológica'), (4, 'Avaliação do Material'), (5, 'Avaliação Social')], verbose_name='Tipo de Avaliação')),
                ('avaliacao_geral', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], verbose_name='Avaliação Geral')),
                ('observacoes', models.TextField(verbose_name='Observações do Avaliador')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='app.estado')),
            ],
            options={
                'ordering': ['estado', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='conscrito',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipio'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(blank=True, choices=[(1, 'Entrevistador(a)'), (2, 'Médico(a)'), (3, 'Dentista'), (4, 'Encarregado de Material'), (5, 'Investigador(a) Social')], null=True, verbose_name='Perfil')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.IntegerField(choices=[(1, 'Pai'), (2, 'Mãe'), (3, 'Irmão'), (4, 'Irmã'), (5, 'Cunhado'), (6, 'Cunhada'), (7, 'Tio'), (8, 'Tia'), (9, 'Sobrinho'), (10, 'Sobrinha'), (11, 'Primo'), (12, 'Prima'), (13, 'Padrasto'), (14, 'Madrasta'), (15, 'Avô'), (16, 'Avó'), (17, 'Bisavô'), (18, 'Bisavó'), (19, 'Sogro'), (20, 'Sogra'), (21, 'Cônjuge/Companheiro(a)'), (22, 'Filho'), (23, 'Filha'), (24, 'Outro')], verbose_name='Parentesco')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('estudante', models.BooleanField(default=False, verbose_name='Estudante?')),
                ('trabalha', models.BooleanField(default=False, verbose_name='Trabalha?')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Renda Mensal')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('trabalha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da empresa e função que exerce')),
                ('estuda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do estabelecimento de ensino e curso que frequenta')),
                ('clubes_associacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do clube ou associação que frequenta e atividade que realiza')),
                ('esportes', models.ManyToManyField(blank=True, to='app.esporte', verbose_name='Esportes que pratica')),
                ('habilidades', models.ManyToManyField(blank=True, to='app.habilidade', verbose_name='Habilidades que possui')),
                ('instrumentos', models.ManyToManyField(blank=True, to='app.instrumento', verbose_name='Instrumentos que toca')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.municipio')),
            ],
            options={
                'ordering': ['conscrito'],
            },
        ),
    ]
