# Generated by Django 6.0.3 on 2026-05-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esporte',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='habilidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='gradefardamento',
            old_name='jaquela',
            new_name='jaqueta',
        ),
        migrations.AlterField(
            model_name='avaliador',
            name='post_grad',
            field=models.IntegerField(choices=[(1, 'Cel'), (2, 'Ten Cel'), (3, 'Maj'), (4, 'Cap'), (5, '1º Ten'), (6, '2º Ten'), (7, 'Asp Of'), (8, 'STen'), (9, '1º Sgt'), (10, '2º Sgt'), (11, '3º Sgt'), (12, 'Cb'), (13, 'Sd')], null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.CreateModel(
            name='BDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('q1', models.IntegerField(choices=[(0, 'Não me sinto triste'), (1, 'Eu me sinto triste'), (2, 'Estou sempre triste e não consigo sair disto'), (3, 'Estou tão triste ou infeliz que não consigo suportar')], verbose_name='1. Tristeza')),
                ('q2', models.IntegerField(choices=[(0, 'Não estou desanimado quanto ao meu futuro'), (1, 'Eu me sinto mais desanimado quanto ao meu futuro do que costumava estar'), (2, 'Não espero que as coisas deem certo para mim'), (3, 'Sinto que meu futuro é sem esperança e que só vai piorar')], verbose_name='2. Pessimismo')),
                ('q3', models.IntegerField(choices=[(0, 'Não me sinto um fracasso'), (1, 'Fracassei mais do que deveria'), (2, 'Ao olhar para trás, vejo muitos fracassos'), (3, 'Sinto que sou um fracasso total como pessoa')], verbose_name='3. Sensação de Fracasso')),
                ('q4', models.IntegerField(choices=[(0, 'Tenho tanto prazer nas coisas como antes'), (1, 'Não aproveito as coisas como costumava aproveitar'), (2, 'Sinto muito pouco prazer com as coisas'), (3, 'Estou completamente insatisfeito')], verbose_name='4. Falta de Satisfação')),
                ('q5', models.IntegerField(choices=[(0, 'Não me sinto particularmente culpado'), (1, 'Sinto-me culpado boa parte do tempo'), (2, 'Sinto-me muito culpado na maior parte do tempo'), (3, 'Sinto-me culpado o tempo todo')], verbose_name='5. Sentimentos de Culpa')),
                ('q6', models.IntegerField(choices=[(0, 'Não sinto que estou sendo punido'), (1, 'Sinto que posso ser punido'), (2, 'Espero ser punido'), (3, 'Sinto que estou sendo punido')], verbose_name='6. Sentimento de Punição')),
                ('q7', models.IntegerField(choices=[(0, 'Não me sinto decepcionado comigo mesmo'), (1, 'Estou decepcionado comigo mesmo'), (2, 'Sinto nojo de mim mesmo'), (3, 'Eu me odeio')], verbose_name='7. Auto-decepção')),
                ('q8', models.IntegerField(choices=[(0, 'Não me sinto pior do que ninguém'), (1, 'Sou crítico comigo mesmo por minhas fraquezas ou erros'), (2, 'Culpo-me o tempo todo por minhas falhas'), (3, 'Culpo-me por tudo de ruim que acontece')], verbose_name='8. Auto-acusação')),
                ('q9', models.IntegerField(choices=[(0, 'Não tenho nenhum pensamento de me matar'), (1, 'Tenho pensamentos de me matar, mas não os levaria adiante'), (2, 'Gostaria de me matar'), (3, 'Eu me mataria se tivesse oportunidade')], verbose_name='9. Ideação Suicida')),
                ('q10', models.IntegerField(choices=[(0, 'Não choro mais do que o habitual'), (1, 'Choro mais do que costumava'), (2, 'Choro o tempo todo agora'), (3, 'Eu costumava ser capaz de chorar, mas agora não consigo nem que eu queira')], verbose_name='10. Crises de Choro')),
                ('q11', models.IntegerField(choices=[(0, 'Não sou mais irritado do que antes'), (1, 'Estou um pouco mais irritado do que o habitual'), (2, 'Estou bastante irritado ou chateado boa parte do tempo'), (3, 'Sinto-me irritado o tempo todo')], verbose_name='11. Irritabilidade')),
                ('q12', models.IntegerField(choices=[(0, 'Não perdi o interesse nas outras pessoas'), (1, 'Estou menos interessado nas outras pessoas do que costumava estar'), (2, 'Perdi a maior parte do meu interesse nas outras pessoas'), (3, 'Perdi todo o meu interesse nas outras pessoas')], verbose_name='12. Isolamento Social')),
                ('q13', models.IntegerField(choices=[(0, 'Tomo decisões tão bem quanto antes'), (1, 'Acho mais difícil tomar decisões do que o habitual'), (2, 'Tenho muito mais dificuldade em tomar decisões do que costumava ter'), (3, 'Tenho problemas para tomar qualquer decisão')], verbose_name='13. Indecisão')),
                ('q14', models.IntegerField(choices=[(0, 'Não sinto que minha aparência esteja pior do que costumava ser'), (1, 'Estou preocupado que pareço velho ou sem atrativos'), (2, 'Sinto que há mudanças permanentes na minha aparência que me deixam sem atrativos'), (3, 'Acredito que pareço feio')], verbose_name='14. Imagem Corporal')),
                ('q15', models.IntegerField(choices=[(0, 'Consigo trabalhar tão bem quanto antes'), (1, 'É necessário um esforço extra para começar a fazer algo'), (2, 'Tenho que me esforçar muito para fazer qualquer coisa'), (3, 'Não consigo fazer trabalho algum')], verbose_name='15. Inibição para o Trabalho')),
                ('q16', models.IntegerField(choices=[(0, 'Consigo dormir tão bem quanto o habitual'), (1, 'Não durmo tão bem quanto costumava'), (2, 'Acordo 1 ou 2 horas mais cedo que o habitual e acho difícil voltar a dormir'), (3, 'Acordo várias horas mais cedo do que costumava e não consigo voltar a dormir')], verbose_name='16. Distúrbio do Sono')),
                ('q17', models.IntegerField(choices=[(0, 'Não me canso mais do que o habitual'), (1, 'Canso-me mais facilmente do que costumava'), (2, 'Canso-me fazendo quase qualquer coisa'), (3, 'Estou cansado demais para fazer qualquer coisa')], verbose_name='17. Fadiga')),
                ('q18', models.IntegerField(choices=[(0, 'Meu apetite não está pior do que o habitual'), (1, 'Meu apetite não é tão bom quanto costumava ser'), (2, 'Meu apetite está muito pior agora'), (3, 'Não tenho mais nenhum apetite')], verbose_name='18. Perda de Apetite')),
                ('q19', models.IntegerField(choices=[(0, 'Não perdi muito peso ultimamente'), (1, 'Perdi mais de 2 quilos'), (2, 'Perdi mais de 4 quilos'), (3, 'Perdi mais de 7 quilos')], verbose_name='19. Perda de Peso')),
                ('q20', models.IntegerField(choices=[(0, 'Não estou mais preocupado com minha saúde do que o habitual'), (1, 'Estou preocupado com problemas físicos como dores, mal-estar estomacal ou constipação'), (2, 'Estou muito preocupado com meus problemas físicos e é difícil pensar em outra coisa'), (3, 'Estou tão preocupado com meus problemas físicos que não consigo pensar em mais nada')], verbose_name='20. Preocupações Somáticas')),
                ('q21', models.IntegerField(choices=[(0, 'Não notei nenhuma mudança recente no meu interesse por sexo'), (1, 'Estou menos interessado em sexo do que costumava estar'), (2, 'Quase não tenho interesse em sexo'), (3, 'Perdi o interesse por sexo completamente')], verbose_name='21. Perda de Libido')),
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bdi', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Resultado BDI',
                'verbose_name_plural': 'Resultados BDI',
            },
        ),
    ]
