# Generated by Django 6.0.3 on 2026-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='data_nascimento',
            field=models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='ra',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Título de Eleitor'),
        ),
    ]
