# Generated by Django 6.0.3 on 2026-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_endereco_complemento_alter_conscrito_cnh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='cnh',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CNH'),
        ),
    ]
