# Generated by Django 6.0.3 on 2026-04-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contato_email_alter_conscrito_cnh'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(default=3550308, on_delete=django.db.models.deletion.CASCADE, to='app.municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliador',
            name='post_grad',
            field=models.IntegerField(choices=[(1, 'Coronel'), (2, 'Tenente-Coronel'), (3, 'Major'), (4, 'Capitão'), (5, '1º Tenente'), (6, '2º Tenente'), (7, 'Aspirante'), (8, 'Subtenente'), (9, '1º Sargento'), (10, '2º Sargento'), (11, '3º Sargento'), (12, 'Cabo'), (13, 'Soldado')], default=1, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
