# Generated by Django 6.0.3 on 2026-04-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_endereco_municipio_alter_avaliador_post_grad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao_Familiar',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('moradia', models.IntegerField(choices=[(1, 'Imóvel Próprio'), (2, 'Imóvel Alugado'), (3, 'Outro')], default=1, verbose_name='Tipo de Moradia')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('sustento', models.BooleanField(default=False, verbose_name='Contribui para o sustento da família?')),
                ('contribuicao', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Valor da contribuição mensal (R$)')),
                ('arrimo', models.IntegerField(choices=[(1, 'Não se enquadra'), (2, 'Filho único de mulher viúva ou solteira, da abandonada pelo marido ou da desquitada, à qual sirva de único arrimo ou o que ela escolher quando tiver mais de um, sem direito a outra opção'), (3, 'Filho que sirva de único arrimo ao pai fìsicamente incapaz para prover o seu sustento'), (4, 'Viúvo ou desquitado que tiver filho menor (legítimo ou legitimado) de que seja único arrimo'), (5, 'Casado que sirva de único arrimo à esposa ou à esposa e filho menor (legítimo ou legitimado)'), (6, 'Solteiro que tiver filho menor (legalmente reconhecido) de que seja único arrimo'), (7, 'Órfão de pai e mãe que sustente irmão menor, ou maior inválido ou interdito, ou ainda irmã solteira ou viúva que viva em sua companhia'), (8, 'Órfão de pai e mãe, que sirva de único arrimo a uma de suas avós ou avô decrépito ou valetudinário, incapaz de prover os meios de subsistência')], default=1, verbose_name='Situação de Arrimo')),
            ],
        ),
        migrations.AddField(
            model_name='conscrito',
            name='rg_orgao_emissor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor do RG'),
        ),
        migrations.AddField(
            model_name='conscrito',
            name='titulo_secao',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Seção Eleitoral'),
        ),
        migrations.AddField(
            model_name='conscrito',
            name='titulo_zona',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Zona Eleitoral'),
        ),
        migrations.AddField(
            model_name='contato',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone_recado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conscrito',
            name='cnh',
            field=models.IntegerField(choices=[(1, 'Não Possuo CNH'), (2, 'Categoria A'), (3, 'Categoria B'), (4, 'Categoria C'), (5, 'Categoria D'), (6, 'Categoria E'), (7, 'Categorias A e B'), (8, 'Categorias A e C'), (9, 'Categorias A e D'), (10, 'Categorias A e E')], default=1, verbose_name='CNH / Categoria'),
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.IntegerField(choices=[(1, 'Pai'), (2, 'Mãe'), (3, 'Irmão'), (4, 'Irmã'), (5, 'Cunhado'), (6, 'Cunhada'), (7, 'Tio'), (8, 'Tia'), (9, 'Sobrinho'), (10, 'Sobrinha'), (11, 'Primo'), (12, 'Prima'), (13, 'Padrasto'), (14, 'Madrasta'), (15, 'Avô'), (16, 'Avó'), (17, 'Bisavô'), (18, 'Bisavó'), (19, 'Sogro'), (20, 'Sogra'), (21, 'Cônjuge/Companheiro(a)'), (22, 'Filho'), (23, 'Filha'), (24, 'Outro')], verbose_name='Parentesco')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('estudante', models.BooleanField(default=False, verbose_name='Estudante?')),
                ('trabalha', models.BooleanField(default=False, verbose_name='Trabalha?')),
                ('renda', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Renda Mensal')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
    ]
