# Generated by Django 6.0.3 on 2026-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_composicao_familiar_conscrito_rg_orgao_emissor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicao_familiar',
            name='arrimo',
            field=models.IntegerField(choices=[(1, 'Não se enquadra.'), (2, 'Filho único de mulher viúva ou solteira, da abandonada pelo marido ou da desquitada, à qual sirva de único arrimo ou o que ela escolher quando tiver mais de um, sem direito a outra opção.'), (3, 'Filho que sirva de único arrimo ao pai fìsicamente incapaz para prover o seu sustento.'), (4, 'Viúvo ou desquitado que tiver filho menor (legítimo ou legitimado) de que seja único arrimo.'), (5, 'Casado que sirva de único arrimo à esposa ou à esposa e filho menor (legítimo ou legitimado).'), (6, 'Solteiro que tiver filho menor (legalmente reconhecido) de que seja único arrimo.'), (7, 'Órfão de pai e mãe que sustente irmão menor, ou maior inválido ou interdito, ou ainda irmã solteira ou viúva que viva em sua companhia.'), (8, 'Órfão de pai e mãe, que sirva de único arrimo a uma de suas avós ou avô decrépito ou valetudinário, incapaz de prover os meios de subsistência.')], default=1, verbose_name='Situação de Arrimo'),
        ),
        migrations.AlterField(
            model_name='composicao_familiar',
            name='contribuicao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Contribuição mensal (R$)'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Renda Mensal'),
        ),
    ]
