# Generated by Django 6.0.3 on 2026-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_composicao_familiar_arrimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='telefone_recado',
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone_pessoal',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='renda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Renda Mensal'),
        ),
    ]
