# Generated by Django 6.0.3 on 2026-04-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_contato_telefone_recado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particularidades',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('relacao_familiar', models.IntegerField(choices=[(1, 'Insuficiente'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], default=3, verbose_name='Relacionamento familiar')),
                ('relacao_social', models.IntegerField(choices=[(1, 'Insuficiente'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], default=3, verbose_name='Relacionamento social')),
                ('sv_militar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alguém da família já serviu às Forças Armadas ou trabalhou em Órgão de Segurança Pública? (Exército, Marinha, Força Aérea, Polícia Militar, Polícia Civil, GCM)')),
                ('armas_fogo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já utilizou qualquer tipo de arma de fogo?')),
                ('voluntario', models.BooleanField(default=False, verbose_name='Deseja servir voluntariamente?')),
                ('voluntario_justificativa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Justifique sua resposta anterior:')),
            ],
        ),
        migrations.CreateModel(
            name='Psicossocial',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('drogas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já consumiu ou consome drogas?')),
                ('jogos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de jogos de azar?')),
                ('movimentos_sociais', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos sociais?')),
                ('movimentos_politicos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos políticos?')),
                ('movimentos_religiosos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Já participou ou participa de movimentos religiosos?')),
                ('osp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Você ou alguém da família já se envolveu com Órgãos de Segurança Pública, mesmo na condição de testemunha?')),
                ('trafico_proximidades', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nas proximidades do local onde reside existem problemas com relação a tráfico ou consumo de drogas?')),
                ('acao_justica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Possui ações na justiça contra o estado ou a nível federal?')),
            ],
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.IntegerField(choices=[(1, 'Futebol'), (2, 'Futsal'), (3, 'Vôlei'), (4, 'Basquete'), (5, 'Handebol'), (6, 'Rugby'), (7, 'Futebol Americano'), (8, 'Beisebol'), (9, 'Tênis'), (10, 'Tênis de Mesa'), (11, 'Badminton'), (12, 'Squash'), (13, 'Beach Tennis'), (14, 'Vôlei de Praia'), (15, 'Judô'), (16, 'Karatê'), (17, 'Boxe'), (18, 'Jiu-Jitsu'), (19, 'Muay Thai'), (20, 'MMA'), (21, 'Esgrima'), (22, 'Taekwondo'), (23, 'Natação'), (24, 'Surfe'), (25, 'Polo Aquático'), (26, 'Remo'), (27, 'Vela'), (28, 'Canoagem'), (29, 'Atletismo'), (30, 'Ginástica Artística'), (31, 'Ginástica Rítmica'), (32, 'Levantamento de Peso'), (33, 'Tiro com Arco'), (34, 'Ciclismo'), (35, 'Skate'), (36, 'Golfe')], verbose_name='Esporte')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esportes', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.IntegerField(choices=[(1, 'Programação'), (2, 'Desenvolvimento Web'), (3, 'Ciência de Dados'), (4, 'Segurança Cibernética'), (5, 'Inteligência Artificial'), (6, 'Banco de Dados'), (7, 'Ferramentas Google'), (8, 'Pacote Office'), (9, 'Edição de Vídeo'), (10, 'Design Gráfico'), (11, 'Marketing Digital'), (12, 'Gestão de Tráfego'), (13, 'Mecânica de Automóveis'), (14, 'Mecânica de Motocicletas'), (15, 'Elétrica de Automóveis'), (16, 'Eletrônica'), (17, 'Elétrica Residencial'), (18, 'Carpintaria'), (19, 'Encanamento'), (20, 'Solda'), (21, 'Marcenaria'), (22, 'Gestão de Projetos'), (23, 'Liderança'), (24, 'Vendas'), (25, 'Negociação'), (26, 'Finanças Pessoais'), (27, 'Recursos Humanos'), (28, 'Oratória'), (29, 'Escrita Criativa'), (30, 'Inglês'), (31, 'Espanhol'), (32, 'Tradução'), (33, 'Primeiros Socorros'), (34, 'Gastronomia'), (35, 'Fotografia'), (36, 'Adestramento de Cães')], verbose_name='Habilidade')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.IntegerField(choices=[(1, 'Violão'), (2, 'Guitarra Elétrica'), (3, 'Contrabaixo'), (4, 'Violino'), (5, 'Violoncelo'), (6, 'Harpa'), (7, 'Ukulele'), (8, 'Cavaquinho'), (9, 'Banjo'), (10, 'Piano'), (11, 'Teclado Sintetizador'), (12, 'Órgão'), (13, 'Acordeom (Sanfona)'), (14, 'Flauta Doce'), (15, 'Flauta Transversa'), (16, 'Clarinete'), (17, 'Saxofone'), (18, 'Oboé'), (19, 'Fagote'), (20, 'Trompete'), (21, 'Trombone'), (22, 'Tuba'), (23, 'Trompa'), (24, 'Bateria'), (25, 'Pandeiro'), (26, 'Cajón'), (27, 'Atabaque'), (28, 'Xilofone'), (29, 'Triângulo'), (30, 'Congas'), (31, 'Tímpano')], verbose_name='Instrumento Musical')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
            },
        ),
    ]
