# Generated by Django 6.0.3 on 2026-04-27 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_composicao_familiar_profissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('trabalha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da empresa e função que exerce')),
                ('estuda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do estabelecimento de ensino e curso que frequenta')),
                ('clubes_associacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do clube ou associação que frequenta e atividade que realiza')),
            ],
        ),
    ]
