# Generated by Django 6.0.3 on 2026-05-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_atividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeFardamento',
            fields=[
                ('conscrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.conscrito')),
                ('calcado', models.PositiveIntegerField(max_length=2, verbose_name='Número do Calçado')),
                ('gorro', models.PositiveIntegerField(max_length=2, verbose_name='Tamanho do Gorro')),
                ('boina', models.PositiveIntegerField(max_length=2, verbose_name='Tamanho da Boina')),
                ('tfm', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme de TFM')),
                ('camuflado', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme camuflado')),
                ('passeio', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho do uniforme de passeio')),
                ('jaquela', models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')], verbose_name='Tamanho da jaqueta')),
            ],
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='relacao_familiar',
            field=models.IntegerField(blank=True, choices=[(1, 'Insuficiente'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento familiar'),
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='relacao_social',
            field=models.IntegerField(blank=True, choices=[(1, 'Insuficiente'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento social'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Avaliação')),
                ('avaliacao_geral', models.IntegerField(blank=True, choices=[(1, 'Insuficiente'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Avaliação Geral')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Avaliador')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.avaliador')),
                ('conscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.conscrito')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
