# Generated by Django 6.0.3 on 2026-05-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gradefardamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.avaliador'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Entrevista'), (2, 'Avaliação Médica'), (3, 'Avaliação Odontológica'), (4, 'Avaliação Social')], verbose_name='Tipo de Avaliação'),
        ),
        migrations.AlterField(
            model_name='gradefardamento',
            name='boina',
            field=models.PositiveIntegerField(verbose_name='Tamanho da Boina'),
        ),
        migrations.AlterField(
            model_name='gradefardamento',
            name='calcado',
            field=models.PositiveIntegerField(verbose_name='Número do Calçado'),
        ),
        migrations.AlterField(
            model_name='gradefardamento',
            name='gorro',
            field=models.PositiveIntegerField(verbose_name='Tamanho do Gorro'),
        ),
    ]
