# Generated by Django 6.0.3 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_avaliacao_avaliador_alter_avaliacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conscrito',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao_geral',
            field=models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Avaliação Geral'),
        ),
        migrations.AlterField(
            model_name='composicao_familiar',
            name='arrimo',
            field=models.IntegerField(choices=[(1, 'Não se enquadra.'), (2, 'Filho único de mulher viúva ou solteira, da abandonada pelo marido ou da desquitada, à qual sirva de único arrimo ou o que ela escolher quando tiver mais de um, sem direito a outra opção.'), (3, 'Filho que sirva de único arrimo ao pai fìsicamente incapaz para prover o seu sustento.'), (4, 'Viúvo ou desquitado que tiver filho menor (legítimo ou legitimado) de que seja único arrimo.'), (5, 'Casado que sirva de único arrimo à esposa ou à esposa e filho menor (legítimo ou legitimado).'), (6, 'Solteiro que tiver filho menor (legalmente reconhecido) de que seja único arrimo.'), (7, 'Órfão de pai e mãe que sustente irmão menor, ou maior inválido ou interdito, ou ainda irmã solteira ou viúva que viva em sua companhia.'), (8, 'Órfão de pai e mãe, que sirva de único arrimo a uma de suas avós ou avô decrépito ou valetudinário, incapaz de prover os meios de subsistência.')], verbose_name='Situação de Arrimo'),
        ),
        migrations.AlterField(
            model_name='composicao_familiar',
            name='contribuicao',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Contribuição mensal (R$)'),
        ),
        migrations.AlterField(
            model_name='composicao_familiar',
            name='moradia',
            field=models.IntegerField(choices=[(1, 'Imóvel Próprio'), (2, 'Imóvel Alugado'), (3, 'Outro')], verbose_name='Tipo de Moradia'),
        ),
        migrations.AlterField(
            model_name='composicao_familiar',
            name='sustento',
            field=models.BooleanField(verbose_name='Contribui para o sustento da família?'),
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='relacao_familiar',
            field=models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento familiar'),
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='relacao_social',
            field=models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Excelente')], null=True, verbose_name='Relacionamento social'),
        ),
        migrations.AlterField(
            model_name='particularidades',
            name='voluntario',
            field=models.BooleanField(verbose_name='Deseja servir voluntariamente?'),
        ),
    ]
