from django.db import models

class Tipo_Avaliacao(models.IntegerChoices):
    ENTREVISTA = 1, 'Entrevista'
    MEDICA = 2, 'Avaliação Médica'
    ODONTOLOGICA = 3, 'Avaliação Odontológica'
    SOCIAL = 4, 'Avaliação Social'

class Post_Grad(models.IntegerChoices):
    CORONEL = 1, 'Coronel'
    TENENTE_CORONEL = 2, 'Tenente-Coronel'
    MAJOR = 3, 'Major'
    CAPITAO = 4, 'Capitão'
    PRIMEIRO_TENENTE = 5, '1º Tenente'
    SEGUNDO_TENENTE = 6, '2º Tenente'
    ASPIRANTE = 7, 'Aspirante'
    SUBTENENTE = 8, 'Subtenente'
    PRIMEIRO_SARGENTO = 9, '1º Sargento'
    SEGUNDO_SARGENTO = 10, '2º Sargento'
    TERCEIRO_SARGENTO = 11, '3º Sargento'
    CABO = 12, 'Cabo'
    SOLDADO = 13, 'Soldado'

class Mencoes(models.IntegerChoices):
    RUIM = 1, 'Ruim'
    REGULAR = 2, 'Regular'
    BOM = 3, 'Bom'
    MUITO_BOM = 4, 'Muito Bom'
    EXCELENTE = 5, 'Excelente'

class CNH_Categoria(models.IntegerChoices):
    NAO_POSSUO = 1, 'Não Possuo CNH'
    A = 2, 'Categoria A'
    B = 3, 'Categoria B'
    C = 4, 'Categoria C'
    D = 5, 'Categoria D'
    E = 6, 'Categoria E'
    AB = 7, 'Categorias A e B'
    AC = 8, 'Categorias A e C'
    AD = 9, 'Categorias A e D'
    AE = 10, 'Categorias A e E'

class Escolaridade(models.IntegerChoices):
    FUNDAMENTAL_INCOMPLETO = 1, 'Fundamental Incompleto'
    FUNDAMENTAL_COMPLETO = 2, 'Fundamental Completo'
    MEDIO_INCOMPLETO = 3, 'Médio Incompleto'
    MEDIO_COMPLETO = 4, 'Médio Completo'
    SUPERIOR_INCOMPLETO = 5, 'Superior Incompleto'
    SUPERIOR_COMPLETO = 6, 'Superior Completo'

class Moradia(models.IntegerChoices):
    IMOVEL_PROPRIO = 1, 'Imóvel Próprio'
    IMOVEL_ALUGADO = 2, 'Imóvel Alugado'
    OUTRO = 3, 'Outro'

class Arrimo(models.IntegerChoices):
    NAO = 1, 'Não se enquadra.'
    FILHO_UNICO = 2, 'Filho único de mulher viúva ou solteira, da abandonada pelo marido ou da desquitada, à qual sirva de único arrimo ou o que ela escolher quando tiver mais de um, sem direito a outra opção.'
    FILHO_PAI_INCAPAZ = 3, 'Filho que sirva de único arrimo ao pai fìsicamente incapaz para prover o seu sustento.'
    VIUVO_COM_DEPENDENTE = 4, 'Viúvo ou desquitado que tiver filho menor (legítimo ou legitimado) de que seja único arrimo.'
    CASADO_COM_DEPENDENTE = 5, 'Casado que sirva de único arrimo à esposa ou à esposa e filho menor (legítimo ou legitimado).'
    SOLTEIRO_COM_DEPENDENTE = 6, 'Solteiro que tiver filho menor (legalmente reconhecido) de que seja único arrimo.'
    ORFAO_COM_DEPENDENTE = 7, 'Órfão de pai e mãe que sustente irmão menor, ou maior inválido ou interdito, ou ainda irmã solteira ou viúva que viva em sua companhia.'
    ORFAO_COM_AVOS_DEPENDENTES = 8, 'Órfão de pai e mãe, que sirva de único arrimo a uma de suas avós ou avô decrépito ou valetudinário, incapaz de prover os meios de subsistência.'

class Parentesco(models.IntegerChoices):
    PAI = 1, 'Pai'
    MAE = 2, 'Mãe'
    IRMAO = 3, 'Irmão'
    IRMA = 4, 'Irmã'
    CUNHADO = 5, 'Cunhado'
    CUNHADA = 6, 'Cunhada'
    TIO = 7, 'Tio'
    TIA = 8, 'Tia'
    SOBRINHO = 9, 'Sobrinho'
    SOBRINHA = 10, 'Sobrinha'
    PRIMO = 11, 'Primo'
    PRIMA = 12, 'Prima'
    PADRASTO = 13, 'Padrasto'
    MADRASTA = 14, 'Madrasta'
    AVO = 15, 'Avô'
    AVOA = 16, 'Avó'
    BISAVO = 17, 'Bisavô'
    BISAVOA = 18, 'Bisavó'
    SOGRO = 19, 'Sogro'
    SOGRA = 20, 'Sogra'
    CONJUGE = 21, 'Cônjuge/Companheiro(a)'
    FILHO = 22, 'Filho'
    FILHA = 23, 'Filha'
    OUTRO = 24, 'Outro'

class ListaEsportes(models.IntegerChoices):
    FUTEBOL = 1, 'Futebol'
    FUTSAL = 2, 'Futsal'
    VOLEI = 3, 'Vôlei'
    BASQUETE = 4, 'Basquete'
    HANDEBOL = 5, 'Handebol'
    RUGBY = 6, 'Rugby'
    FUTEBOL_AMERICANO = 7, 'Futebol Americano'
    BEISEBOL = 8, 'Beisebol'
    TENIS = 9, 'Tênis'
    TENIS_DE_MESA = 10, 'Tênis de Mesa'
    BADMINTON = 11, 'Badminton'
    SQUASH = 12, 'Squash'
    BEACH_TENNIS = 13, 'Beach Tennis'
    VOLEI_DE_PRAIA = 14, 'Vôlei de Praia'
    JUDO = 15, 'Judô'
    KARATE = 16, 'Karatê'
    BOXE = 17, 'Boxe'
    JIU_JITSU = 18, 'Jiu-Jitsu'
    MUAY_THAI = 19, 'Muay Thai'
    MMA = 20, 'MMA'
    ESGRIMA = 21, 'Esgrima'
    TAEKWONDO = 22, 'Taekwondo'
    NATACAO = 23, 'Natação'
    SURFE = 24, 'Surfe'
    POLO_AQUATICO = 25, 'Polo Aquático'
    REMO = 26, 'Remo'
    VELA = 27, 'Vela'
    CANOAGEM = 28, 'Canoagem'
    ATLETISMO = 29, 'Atletismo'
    GINASTICA_ARTISTICA = 30, 'Ginástica Artística'
    GINASTICA_RITMICA = 31, 'Ginástica Rítmica'
    LEVANTAMENTO_DE_PESO = 32, 'Levantamento de Peso'
    TIRO_COM_ARCO = 33, 'Tiro com Arco'
    CICLISMO = 34, 'Ciclismo'
    SKATE = 35, 'Skate'
    GOLFE = 36, 'Golfe'

class ListaHabilidades(models.IntegerChoices):
    PROGRAMACAO = 1, 'Programação'
    DESENVOLVIMENTO_WEB = 2, 'Desenvolvimento Web'
    CIENCIA_DE_DADOS = 3, 'Ciência de Dados'
    SEGURANCA_CIBERNETICA = 4, 'Segurança Cibernética'
    INTELIGENCIA_ARTIFICIAL = 5, 'Inteligência Artificial'
    BANCO_DE_DADOS = 6, 'Banco de Dados'
    FERRAMENTAS_GOOGLE = 7, 'Ferramentas Google'
    PACOTE_OFFICE = 8, 'Pacote Office'
    EDICAO_DE_VIDEO = 9, 'Edição de Vídeo'
    DESIGN_GRAFICO = 10, 'Design Gráfico'
    MARKETING_DIGITAL = 11, 'Marketing Digital'
    GESTAO_DE_TRÁFEGO = 12, 'Gestão de Tráfego'
    MECANICA_AUTOMOTIVA = 13, 'Mecânica de Automóveis'
    MECANICA_MOTOCICLETAS = 14, 'Mecânica de Motocicletas'
    ELETRICA_AUTOMOTIVA = 15, 'Elétrica de Automóveis'
    ELETRONICA = 16, 'Eletrônica'
    ELETRICA_RESIDENCIAL = 17, 'Elétrica Residencial'
    CARPINTARIA = 18, 'Carpintaria'
    ENCANAMENTO = 19, 'Encanamento'
    SOLDA = 20, 'Solda'
    MARCENARIA = 21, 'Marcenaria'
    GESTAO_DE_PROJETOS = 22, 'Gestão de Projetos'
    LIDERANCA = 23, 'Liderança'
    VENDAS = 24, 'Vendas'
    NEGOCIACAO = 25, 'Negociação'
    FINANCAS_PESSOAIS = 26, 'Finanças Pessoais'
    RECURSOS_HUMANOS = 27, 'Recursos Humanos'
    ORATORIA = 28, 'Oratória'
    ESCRITA_CRIATIVA = 29, 'Escrita Criativa'
    INGLES = 30, 'Inglês'
    ESPANHOL = 31, 'Espanhol'
    TRADUCAO = 32, 'Tradução'
    PRIMEIROS_SOCORROS = 33, 'Primeiros Socorros'
    GASTRONOMIA = 34, 'Gastronomia'
    FOTOGRAFIA = 35, 'Fotografia'
    ADESTRAMENTO_DE_CAES = 36, 'Adestramento de Cães'

class ListaInstrumentos(models.IntegerChoices):
    VIOLAO = 1, 'Violão'
    GUITARRA = 2, 'Guitarra Elétrica'
    BAIXO = 3, 'Contrabaixo'
    VIOLINO = 4, 'Violino'
    VIOLONCELO = 5, 'Violoncelo'
    HARPA = 6, 'Harpa'
    UKELELE = 7, 'Ukulele'
    CAVAQUINHO = 8, 'Cavaquinho'
    BANJO = 9, 'Banjo'
    PIANO = 10, 'Piano'
    TECLADO = 11, 'Teclado Sintetizador'
    ORGAO = 12, 'Órgão'
    ACORDEON = 13, 'Acordeom (Sanfona)'
    FLAUTA_DOCE = 14, 'Flauta Doce'
    FLAUTA_TRANSVERSA = 15, 'Flauta Transversa'
    CLARINETE = 16, 'Clarinete'
    SAXOFONE = 17, 'Saxofone'
    OBUE = 18, 'Oboé'
    FAGOTE = 19, 'Fagote'
    TROMPETE = 20, 'Trompete'
    TROMBONE = 21, 'Trombone'
    TUBA = 22, 'Tuba'
    TROMPA = 23, 'Trompa'
    BATERIA = 24, 'Bateria'
    PANDEIRO = 25, 'Pandeiro'
    CAJON = 26, 'Cajón'
    ATABAQUE = 27, 'Atabaque'
    XILOFONE = 28, 'Xilofone'
    TRIANGULO = 29, 'Triângulo'
    CONGAS = 30, 'Congas'
    TIMPANO = 31, 'Tímpano'

class Tamanhos(models.IntegerChoices):
    P = 1, 'P'
    M = 2, 'M'
    G = 3, 'G'
    GG = 4, 'GG'